### PR TITLE
1. Added Footer and Metrics component to Components directory

### PR DESCRIPTION
**Pull request by jpatterson933**
Adjusted Layout.jsx to include new <Footer /> element on the bottom. Removed footer styling from index.css in src directory and put the styling inside /Footer/index.css - then adjuste styling and added link to github repository

### CODE REVIEW

**Comment by StephenODea54** [comment]
I think everything looks good. I'm also cool with having an `index.js` for each component. If we go this approach, however, we should probably think about a better directory layout than the one we currently have. Though I don't usually like putting components into their own module for the sake of it (for example, I have the `BlogComponent` component inside of the `Blog` component because that's the only place that component is going to live and hence doesn't make sense to have it be anywhere else besides inside of the `Blog` component), but I'm down to do your style since it seems like that is what most people do.

So here's what we have right now:
  - `pages` which holds each individual page, and
  - `components` which holds the individual components used on each page.
  - `Layout.jsx` which serves as a wrapper for each page (this is in it's own component because each page uses it).
 
I think the easiest way to set up the directory (so it's easier to follow along with and that it's uniform across the code base), is:
  - components
    - about
      - `index.jsx`
    - blog
      - `index.jsx`
      - `BlogComponent.jsx`
    - metrics
      - `index.jsx`
      - `Metrics.jsx`
    - posts
      - `index.jsx`
    - layout
      - `index.jsx`
      - `Footer.jsx`

I'm still going to approve because this stuff really isn't a huge deal atm, but it's something we should think about as our app gets bigger.

**Review by StephenODea54 — APPROVED** [review]

**Comment by jpatterson933** [comment]
@StephenODea54 

I agree, I'm going to update the file structure to match how its setup. 

I was thinking 

Component -> Pages -> Layout -> App.js -> index.html

**Comment by jpatterson933** [comment]
Going to redo this branch and push into a new branch with a layout that is consistent.

**Comment by StephenODea54** [comment]
@jpatterson933 sounds good! Thanks!

**Pull request closed without merging**
